### ISSUE TITLE
MissingFeature:当粘贴遇到中文字符时，似乎不会粘贴，而是直接跳过？

### ISSUE THREAD

**Issue by smanliy** [Octopustank/TextInputUtility#1]
1. 在text.txt中书写 我爱学习，运行程序，没有输出结果
2.在text.txt中书写 我爱学习1234，运行程序,输出结果为1234，没有前面的中文
没有搞懂，也许是我操作的问题？

**Comment by Octopustank** [comment]
python的`pyautogui.write`不支持输入中文。因为它模拟输入ASIC II码进行输入的。
这是目前来看不可解决的问题😅

所以麻烦尽量自己输入中文吧。感谢提醒，这一点我在README中忘记写入了

**Comment by Octopustank** [comment]
> python的`pyautogui.write`不支持输入中文。因为它模拟输入ASIC II码进行输入的。
> 这是目前来看不可解决的问题😅
> 
> 所以麻烦尽量自己输入中文吧。感谢提醒，这一点我在README中忘记写入了

已经修改了README.md，增加了这一点的说明。谢谢提醒

**Comment by smanliy** [comment]
> > python的`pyautogui.write`不支持输入中文。因为它模拟输入ASIC II码进行输入的。
> > 这是目前来看不可解决的问题😅
> > 所以麻烦尽量自己输入中文吧。感谢提醒，这一点我在README中忘记写入了
> 
> 已经修改了README.md，增加了这一点的说明。谢谢提醒

谢谢谢谢谢谢谢
